MESSAGE(STATUS "Using bundled Find libcryptopp ...")

FIND_PATH(
  CRYPTOPP_INCLUDE_DIR
  cryptopp/cryptlib.h
  /usr/include
  /usr/local/include/
  )

FIND_LIBRARY(
  CRYPTOPP_LIBRARIES NAMES  cryptopp
  PATHS /usr/lib/ /usr/local/lib/
  )

IF (CRYPTOPP_INCLUDE_DIR AND CRYPTOPP_LIBRARIES)
  SET(CRYPTOPP_FOUND 1)
  INCLUDE_DIRECTORIES(${CRYPTOPP_INCLUDE_DIR})
ELSE (CRYPTOPP_INCLUDE_DIR AND CRYPTOPP_LIBRARIES)
  SET(CRYPTOPP_FOUND 0)
ENDIF (CRYPTOPP_INCLUDE_DIR AND CRYPTOPP_LIBRARIES)

MARK_AS_ADVANCED(
  CRYPTOPP_INCLUDE_DIR
  CRYPTOPP_LIBRARIES
  )
